### ISSUE TITLE
Use FireCloud UI for Export

### ISSUE THREAD

**Issue by coverbeck** [BD2KGenomics/boardwalk#11]
At F2F it was discussed that FC will have a UI to import Bagit that Windmill will use. Boardwalk should redirect to the same UI.

This will not happen until July at the earliest.

This will require us to have the url for the bagit.

As part of this, we will need to persist the bagit so that we can redirect to FireCloud, passing a URL to FireCloud that references the bagit.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/BOARD-5)
┆Project Name: Boardwalk-UI
┆Issue Number: BOARD-5
┆Epic: Epic 8: “Handoff” From Portal to Workspace

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

From demo, looks like the url we redirect to should be:

https://bvdp-saturn-prod.appspot.com/#import-data?url=<url>
