### ISSUE TITLE
Boardwalk - overview of work in 2018

### ISSUE THREAD

**Issue by natanlao** [BD2KGenomics/boardwalk#13]
Issue moved |
---|
This issue was moved from [dcc-ops/BD2KGenomics#134](https://github.com/BD2KGenomics/dcc-ops/issues/134). |

CC wireframes demo

┆Issue is synchronized with this [JIRA Epic](https://ucsc-cgl.atlassian.net/browse/BOARD-7)
┆Project Name: Boardwalk-UI
┆Issue Number: BOARD-7

**Comment by cricketsloan** [comment]
➤ Cricket Sloan commented:

This seems like an empty ticket
