### ISSUE TITLE
Connect Boardwalk to ElasticSearch index for Commons

### ISSUE THREAD

**Issue by mikebaumann** [BD2KGenomics/boardwalk#5]
Adapt Boardwalk’s web service to read from our custom index for Commons
[Check status with Carlos]

Supports epic DataBiosphere/administration#30

**Comment by mikebaumann** [comment]
Move this issue to dcc-dashboard-service

**Comment by mikebaumann** [comment]
This is implemented and overall appears to be working. However, when a facet is selected no results are shown. This needs to be fixed before this task is considered done.

**Comment by coverbeck** [comment]
The problem with the facets was fixed. This is now working
