### ISSUE TITLE
Allow Boardwalk Client to Make API Calls Relative to the Domain

### ISSUE THREAD

**Issue by cricketsloan** [BD2KGenomics/boardwalk#62]
In feature/commons branch, the UI currently makes API calls using a fully qualified urls, where the base of the url comes from the UI's node.js server.

The UI should just use relative urls, which will be resolved relative to the host the UI is running on.

To get this working when running the UI locally, the UI can take advantage of the [proxy feature](https://juristr.com/blog/2016/11/configure-proxy-api-angular-cli/) in Angular CLI.

Doing this will a step towards getting rid of the UI's node.js server, and will also enable the UI to be deployed on s3/CDN.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/BOARD-54)
┆Project Name: Boardwalk-UI
┆Issue Number: BOARD-54
┆Epic: Google authn for Boardwalk

**Comment by NoopDog** [comment]
Pull request
https://github.com/DataBiosphere/cgp-boardwalk/pull/64
