### ISSUE TITLE
Commons auth functional spec updates

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [BD2KGenomics/boardwalk#78]
┆Issue is synchronized with this [JIRA Task](https://ucsc-cgl.atlassian.net/browse/BOARD-63)
┆Project Name: Boardwalk-UI
┆Issue Number: BOARD-63

**Comment by NoopDog** [comment]
Hi @coverbeck anything else to be done here for the time being? If not can you close this please. Thanks!
