### ISSUE TITLE
Show portal data or “How to Register” page depending on if user is whitelisted

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [BD2KGenomics/boardwalk#86]
┆Issue is synchronized with this [JIRA Task](https://ucsc-cgl.atlassian.net/browse/BOARD-71)
┆Project Name: Boardwalk-UI
┆Issue Number: BOARD-71

**Comment by NoopDog** [comment]
HI Charles, this one is implemented as well and should be closable once the code is deployed to dev. Cheers,D
