### ISSUE TITLE
Homepage says there is restricted access data when there isn't

### ISSUE THREAD

**Issue by cricketsloan** [BD2KGenomics/boardwalk#92]
This probably some residual config stuff in the deployment process that needs to be re-overwritten.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/BOARD-76)
┆Project Name: Boardwalk-UI
┆Issue Number: BOARD-76

**Comment by coverbeck** [comment]
This was opened in the wrong repo. Closing...
